import { type Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import Link from "next/link";
import "~/styles/globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const geist = Geist({ subsets: ["latin"], variable: '--font-geist' });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
 return(
  <nav className="flex w-full items-center justify-between border-b p-4 text-x1 font-semibold ">
    <Link href="/">
      Home
    </Link>
    <Link href="layer2">
      Layer2
    </Link>
  </nav>
 )
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className={`font-sans ${inter.variable} flex-col gap-4`}>
        <TopNav />
      <body><div className="w-full">First Layout</div>{children}</body>
      </body>
    </html>
  );
}
