import { type Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import Link from "next/link";
import "~/styles/globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import {TopNav} from "./_components/topnav";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const geist = Geist({ subsets: ["latin"], variable: '--font-geist' });

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Wathan",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
      <body className={`font-sans ${inter.variable} flex-col gap-4`}>
        <TopNav/>
        <div className="w-full">First Layout</div>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
